### ISSUE TITLE
Clearing persistent data?

### ISSUE THREAD

**Issue by lucianthorr** [confluentinc/cp-all-in-one#63]
**Description**
I've been using the cp-all-in-one docker compose environment for a few days and it is now crashing with the following error 
"Disk error when trying to access log file on disk"

I do notice that the environment persists topics between "docker-compose up" and "docker-compose down" so wherever it's writing to, it's probably filling up.

How can I clear it?  `docker system prune` does not seem to help and I don't see it mounting any volumes in the docker-compose.yaml

**Environment**
 - GitHub branch: 6.0.1-post
 - Operating System: macOS 10.15.7
 - Version of Docker: docker 20.10.2
 - Version of Docker Compose: 1.27.4

**Comment by awalther28** [comment]
Hello again :) 

Generally `docker system prune -a` will clear out more. WARNING ⚠️  adding the `-a` flag will remove ALL unused images, not just dangling ones, so please use with care! 

This demo isn't meant to run that long, which is why we don't use volumes. It's meant for quicker validations and highlighting product functionality. If you do want to run CP on docker for longer periods of time, I suggest checking out this page on how to [mount volumes](https://docs.confluent.io/platform/current/installation/docker/operations/external-volumes.html). 

To help improve memory limitations you might be hitting, I would suggest looking at the topic configurations and broker level configurations regarding retention. If you don't need the broker logs, you could really limit the retention there to make room. Same thing for topic data. Please note that this advice is coming from the perspective that this is a dev/"throw away"  environment.

**Comment by awalther28** [comment]
That's a great questions :) I don't have an answer for you at the moment but I will get back to you!
